### ISSUE TITLE
Civil 3D 2017 Version

### ISSUE THREAD

**Issue by Kapanther** [ADN-DevTech/Civil3DSnoop#4]
Thoughts on a 2017 version? is there much that needs to be done to make it happen?

**Comment by augustogoncalves** [comment]
It should be compatible, probably just change the PackageContents.xml to allow load on 2017.

**Comment by LightosTomJ** [comment]
The code segment below was UNSUCCESSFUL for the amended "PackageContents.xml". I don't know the correct version number. You'll have the change "PackageContents.txt" to "PackageContents.xml".

Perhaps someone could point me in the correct direction?

[PackageContents.txt](https://github.com/ADN-DevTech/Civil3DSnoop/files/456255/PackageContents.txt)

**Comment by augustogoncalves** [comment]
Please see 2017 branch

**Comment by LightosTomJ** [comment]
Cheers Augusto. 

-------- Original message --------
